[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "68719aad72de6e1620ec773da451446091a2e47c"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "19d71c82bf7a755ad98e7a7397b97bc5165f17d3fd73e2a42e8739b637a35505"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "89f7759f568b024d28285b83624860bc05d81c0b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "907a2d26cea52b8d3ba63ebd6a7e0dc41f9c2189783705901879dcfbf4699ff4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "5a48c74413a6582d5bfda664d7c8a210db684a20"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "d1df2fb599fdf74c99b8b5107d537b89748223b62488ca2d74c97fd1c8528a4b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "716053db7547b4b9f166ead345f4483ecbb64e00"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "0df9fc36aaf27bc1bc0503d3cc64a0db753abfe07115917b0f4f4f3d715376d9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "bc6288864a443648553530537a0e2212dc0d071c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "b0d3b64d87906d2d54bebad347223cdd5e036799f64d633eb26a74aeb6b6d2a7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "riscv64"
git-tree-sha1 = "58944b874ed88bd962f0f965493f7ae58938fe79"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "2c88c9318fa9438dc2fd0b13c1acceeab90b693618da1541a6d3f805bda622b6"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "44a3a898f4359d5962aafeafbcda7c9ba979a192"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "7a0aeb6e4bb7729146a9854846ec41b3fd3c9e841790a2ccab68610a200f4496"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "84aaf78da7ce7643f9dd7bb8d8835dbc70964b5b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "82f1254a411f331e15525e3d714898663233eb39298ddc8ad5fa05958bcad01c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "70097c9fee9190a8322d86a01ab1cdf8ed5a9632"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "8e2afc4be406b46231eb0d90479283d3349fad4f39474b5aacdeb009a83010b5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "8a97492342064746d07bcf08f1f831a90f0443fb"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "c2841cab44960933eb6b45de8c866943ebac46b534b21a3953a62192b0542fa9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v101.30800.0+0/GAP_pkg_edim.v101.30800.0.x86_64-unknown-freebsd.tar.gz"
