[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "dd89aafb8fb1d675562f7560e21a46c22b330dc3"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "08b23b4a2a77c39fffe4fadd35ae41cb03212fdd90961bfba710a79fef7898e1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "ea3b40062c60de037aacbf6235e025476281849b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "f56217eeb6ed05ee226a575182027f621e4023368b5d903b0226ced0bc650a9a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "7dd3c218b81808060237bd513c852c1647f43f6c"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "486c49f8ca3f0d7b5be45e0fd80063d0f509c36228c7bd8f73f61a70f0a27374"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "850f2986001223d5d2b711a00cff263cf491b95c"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "bed1343623e7bac8fac33c3bb1479c85287c53655995cfa3a8337281ed8c0f84"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "f3dae8285cb53c97db5ed9977902e27aadf5758d"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "0495455c4854f6ec80c1706771d53dc2dcec78107d02f56b3a2fede27fe0c971"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "23a7be79794c5585e21e810b7e11d6bb67fa482a"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "aec98828fdc062b7e8c5cf7405d6864904c072d3586cee72cbf318fe5228af78"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "8f4ded3f5c739578035dd27a77d987d845ebaae9"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "acd7814a89ececa0cefc0ca0dcfe406ca98810b81661d9e156ad3ff84cace35a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "173549a8a627c620bfbee907541fe35cc2b32daa"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "fa36e04a09b19afeea4ab15ab42f36496e3762ce1fbaa364156f928270c650b2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.800+0/GAP_pkg_edim.v100.300.800.x86_64-unknown-freebsd.tar.gz"
