[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "3583a5e4040e1c23e486fc36c5264f189008c9ba"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "be5445723be65f2aef97582a26049d021b51aa4d28ad606b871f7f53f79cf15f"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "b2969f16a30e9da93e49c8c3e7f752fcf3f910bd"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "09988c778a4572f7c39a4408ea787088344410e41e4c4925583e98fb294e8de2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "38c0b5c42f724e863b6eb90c8e3d45baf42c7093"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "00c88f334239fe41adf4740c5e39cee71951350d390b34df19636e00dbb3e92e"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "8459937a8a88e70f1b2f644072dfc6d00cfec74a"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "b13eb2912347349c778d6c09d39ec530ff06f983e97562565c493d100a296212"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "ec1cbd99a6d0b620e87a4569bd9e1532f241cd56"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "8d5cfb4a07ad5cadae13913ae7f112ed029116b9f994910dd8271fb234d690e3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "riscv64"
git-tree-sha1 = "85aef56ffb2e18c400098f5a13966842a7903599"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "56ff394f0aa9c9328d0f74bac6424d41693ea1ad7ae151d1ad5802c5317d86d9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "fc581d49800b5354cc489d5a5ae1cda12c5ca569"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "17a1ce61d0d637bb2bde39c5fe4e073bc890948e6dd9556744098af8e2a03b69"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "b059bfd4fce8c6af22f6371e3247084933904f9f"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "37dff252d26d855afa1d83a181c5af3b3b02a31392b474554505aa5bbc13145c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "2ca78b77a093d2bfecf6ccd49cf24676ee88d7da"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "92984abeabc1c9d89b08fd4c66c7c3f950acfc72e3bdf9de1ebae83d762a0d79"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "ca68b5914039736a1d4aa4b3dc4b4d91762974ff"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "2c6da02df8d5ca155ed668c9c5758b4a7788a9a75a82df2a9ab85da75254eeab"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.803+0/GAP_pkg_edim.v100.300.803.x86_64-unknown-freebsd.tar.gz"
