[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "a4ae66afa07ae72abba221911f6235bb14ea54eb"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "d92d2060d253ba395f6e0251fabdfb4559ebf4de01536bac5fbd8f8bf18bccfb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "43fee45c7b6e44522097cdc95a45d28df7141c1d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "0ad421816fcd1f8c5a8ebe9c5d813317bbde5255870bc505ffe96016d791c1eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "7dcd3e347ed54cb43aa0e9e4d2a811b0a7970115"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "0212ffc6351ca3eabdc615ee13341417d2f6bcc345f466c12f3b176e4ec09dff"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "98101cb761c7f539e1b244ce239683368621d40d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "d4fcbd2e7ee1a5082498d82786c4e9a59f76222d20aaaf6f8ffb23dd05d1eddf"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "76c73302a7062674a7eaceca92f6e5f5e3942095"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "d256761eeb729c18e4ca70f1f78014676be853ab40843eaae7426e954dfc7a7d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "d11a0d887af5dccd41cee73a507d2cd0382c5390"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "451a1c3a1eab3d9a3a51cd5133ea1d702f51dd497fe2248a5aaf27abeb513bff"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "316b8f056fa1bb61f1bbe7b31ac4407bf0224f51"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "6d9729fb893c6f9c737f57812d10c2db0f787be36ffee8fd3053fe2492742c6d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "7776741f70938a1802f3353b5f0f019057c6ed79"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "db4191f86bc3f1dd2ad23e6f878bfe34d8c4d0f03d9e8dfb426a6ff8dbcb33e5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+1/GAP_pkg_edim.v100.300.801.x86_64-unknown-freebsd.tar.gz"
