[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "3e1da1654fcd3600cfd13c796bb6a9938e6f43b8"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "a949020555295d0ced91e15ac32fbc59a3d9813837d10f4fa620923872108095"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "64cac6925408ca12c6d44ba0f8cf0c592d435f74"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "50abc498ada01c63d28c748809f698ac89f6bee82acf18ae8ffa3a2ba40f49fc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "32575688a25cf56a1dc6cb2ee60e769144b9cc2f"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "30416ebff26b34da849b0d1eea1dc6036d1cc143506f73e5fa27612e75483189"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "0d2633edffde9cc321a2ed4b5c46446c2abdf64e"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "f908ef72064786c2892e1bc1e0336122a0f1b08de583a765c65e9ba796fba59a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "222e8437ee148aae4183221bf5344aaa639510ec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "afdb3e5a91aebb4bfc27b42b4acb235bd0e997ee4b90b077e3f178847050b1dc"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "riscv64"
git-tree-sha1 = "4421d9329162cce25d2bff2baf956a1782ffdfc4"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "2dc0bfe6be3103c0b2fba0295a60ecafb1f01cb80a5f0f7c52a199060e4a2938"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.riscv64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "f0de3a0d21a3a8316188880a02f9efb24e9c6af6"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "1d44378f8ab34c4e919a10217e6f84396fa7dfe0f96f89011baea737614d6554"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "93467b8f735c3717cb6907b10286d21b5b1d7f83"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "9a252a388c78874c8cfa3f8f37cc8544158b678d9f54ef6338fe31b24a33584d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "2a868cd0c25d7e9cade5b28e4ac46017c1fa30d3"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "97c19e01d4d7f249a32b92f5fd5ae0eb980c9f2f32140884d22330ebdbf3ad40"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "471764b01f2cb6eda57cf7999138c4ada78ad841"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "0f2753ddb447c03c0bba62f68769c29d9fe34b09f636c02b54fff1c7b8b69caa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.802+0/GAP_pkg_edim.v100.300.802.x86_64-unknown-freebsd.tar.gz"
