[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "463838f045911014f5643ba43c511a494e01eda8"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "47dddab3dac2ed5d42f8166e66c7517998aa50624521f08668c4073c3ba5eea3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "309cba8bdc07dfdabbd5409842cd69179b1b6002"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "c44768a6e30a1592e97d723d9cd6c8cbfe89038f1408ddd6beb687f0ba20d58a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "e74298f3e1cf0cd99a1df1f002f49caeca33d15b"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "c1a2dcc154917bc141e12b8d302b8a06b0721329175d60d0a1e5bdc6498753ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "6b57cd17c699df4dc726877fbaf2b36369e25385"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "8f92c71cf01588d395a1433dd41f2d76c7d19dbd9b656beda4f0f4e633c4746b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "6a54ce14c75debb974a39a9edd44f6f86021b840"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "800aa30160e46ca42d4f1116dfb4a996e20079cbb7a0a722f266352749ce9666"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "c79e2fdffea4701e344657c207f000fcbfe13758"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "43c9688ebf40c7ffce39a34ed807b1e8cc9a8aec78edc70ed8a47b7c736c5bea"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "31cfc071736f5428563c3d0848239231f00ee243"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "0ce284f1c04127af1cab6b28b72de8b3444f4b96b612d0c11d7b88736db0fcf2"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.500+0/GAP_pkg_edim.v100.300.500.x86_64-unknown-freebsd.tar.gz"
