[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "e14a9eb96ffb153cfee28a10c446859911a2140c"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "d8020e652fa03bd4b0b462e975da92ad75643d38f12b287a28a5f1ff573f4cd5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "3bbc0799de7fc737738e4399188b8c87717e3dd0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "9b26049cb00dca3cb5e52ddbd0e16a4ce4680357c2a4ccef4e95dd3a1c09736d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "a2f4843a644511d9328d7ad68c38faee41e1dd81"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "c9b2ec4d76077a15397e23a65ca373346d017483cb494ad342f44c976050e70b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "dd80554b8004b47c251c5675fb73b19a16fa85b7"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "96bcaed71fc1b5c3b572638196bf7bc6b0c23f6789ee723769231e923845d6c1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "4d7eee32218afe8775eade8caf00a9834f70c233"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "6008aa46aa5493e39a03190817612fd4c3a135aff48ca3c7f535b09dced7db35"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "dc2ab5fed9eadf21bdd9799a8679a579bd52f3ec"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "8c4bd9d0ad73a09965d84417cbc19fc980ecfed2427b28387b8a981ad2e9dfb8"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "437073c4044d4568d7e32d50434ebab886a12c19"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "cf7a97fc942c073ab322a1e3a77e53b48ee94ff9fbc31b83c6e451d45afd915b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "f56caefc16991ce5312ff1b22b2270f7fcb6e6b5"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "b7fcd3c436cc580cbff12b49b1292fa4ad16e03c7ce9f9ebbc944eb3e430cdc1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.502+1/GAP_pkg_edim.v100.300.502.x86_64-unknown-freebsd.tar.gz"
