[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "4d8a2cabc5ee52bfe0f1e37ed5b40359231ae243"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "a1b0b2ab2acf62f909f83c5465ed0c93698a3e5a472a0ed5cc2cbb76ad8a053b"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "b8f1ddf0834b34adf3be10457abd46f6c50136e0"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "fd992c46acfdf14f1de3c4e7e6ea23011829c0f1cf79964f1d03d96fd3fd9a77"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "f4a9228072145201ce6be3b6774efb21768400da"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "8cb6fe12761c2f6e0c4ec1630f585b0c4fdae10140e5ec9a19059062442faf08"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "d4def79c3502deb8d4f6d45fb67884ae317854c2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "35bbad2d654b2f56725250f4648f668f9e5e51a32f7e49cf7f78b5115ef8e4e7"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "59f9c74362a0336fb7938ef089d7d2763e7fab91"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "56487bc1b712c85eb172b687c07e78ff1d1da0535ba455293d6cf0520c9adabd"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "28ae3f52691f6852377bcf48c9ec18f0197168e5"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "54cf3543caa38b60c7bf220fcb735f4ae4135314ea38218b8c69c64e00dd48d1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "be5d1b57ce58c37ea5aad89fc93e93e3b52b6c4b"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "ed0a5219e96990bd788fe62dcff346d11529810ffbae643504e506e3c95e51a5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "ad911012671e585b7303e6559fd993db704b7d2a"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "c8f949a61824cbc33669274d2c081a6449c96459f30d39684bd0553e0e6613eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.600+1/GAP_pkg_edim.v100.300.600.x86_64-unknown-freebsd.tar.gz"
