[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "88ba828d9e639e1643d745fd6ad068aa6d9b7bd0"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "26faa9d120c649631b3bd7a784a63fe1cef33cb6e8f626c6c15268df8bffb28d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "2f1df1ecef563d32f48950691f53e2d19126dcb1"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "4b9c2cd24741fb9665ccdcced648ce251450b4f11d30730c513591976215b976"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "aarch64"
git-tree-sha1 = "a9864e631657ad04fa86c25f88388ab36a97bea9"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "bc9214a1d9ed743a2a96c054f66dd3c8ea22dac5b90c2db243f8ff6164ed19ef"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.aarch64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "powerpc64le"
git-tree-sha1 = "5c5d93cf444e349aa04cc50ce31d03fe35714924"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "a1ea2da8f89d556e8f02dfd010723248dc473d97764cdffd771b77319b57ad6c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "b36c594efa7ada98a472339246b2602c5d227f05"
os = "macos"

    [[GAP_pkg_edim.download]]
    sha256 = "6e31031bce49bbd10d3981e6339ff190162f96316e7541621bbe9eebb74a7dd1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "0009f437a5ecb163a24cc1bfffbf2339221e3b84"
libc = "glibc"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "c3828106064acca8afe8da92f3a5694f4185a504a4c9be4daab866daee7e011d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "f2d9b4b0254051533f7b709f0e83919a1b432bef"
libc = "musl"
os = "linux"

    [[GAP_pkg_edim.download]]
    sha256 = "536876804450d71550caaacfc6bf585f14b959e788d0103e30a569df5c3a756c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.x86_64-linux-musl.tar.gz"
[[GAP_pkg_edim]]
arch = "x86_64"
git-tree-sha1 = "30c49e855d9a9cf500da028ef482f3e68a756ac4"
os = "freebsd"

    [[GAP_pkg_edim.download]]
    sha256 = "c976892f14170bb7990be7b04e10d664995c7c9b43e6098530a38e30e2303575"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_edim_jll.jl/releases/download/GAP_pkg_edim-v100.300.801+0/GAP_pkg_edim.v100.300.801.x86_64-unknown-freebsd.tar.gz"
